### ISSUE TITLE
Unchecked runtime.lastError: OAuth2 request failed: Service responded with error: 'bad client id

### ISSUE THREAD

**Issue by sajarin** [shihabdider/flowwatch#1]
Currently the app is unable to authorize with Google Calendar (clicking the authorize button should redirect to an oauth consent screen i.e Flowwatch wants to access your Google Account... but nothing happens upon click)

Current client id according to the manifest.json is: 
`579547506966-hriv9n6a30e9lkmr0r99s0uhneonhof7.apps.googleusercontent.com`

**Comment by shihabdider** [comment]
In the extensions page on chrome (accessed via 'Manage Extension') what does the `ID` field show? It may be that because it hasn't been uploaded to the web store it has a different ID than what is set in the OAuth credential.

**Comment by sajarin** [comment]
The id under the extension is `cnhndljacfgpicheeflbbllbiakpjiej`

The current client id that is being marked as bad is `831012186265-77mueug86fvaa1hh5af7ad4vh6gvvllk.apps.googleusercontent.com`

**Comment by shihabdider** [comment]
OK that means the client-id is changing upon install. It seems like a 'key' field has to be generated and included in the manifest.json to keep this field consistent between installations. I'll fix this and push.

**Comment by shihabdider** [comment]
The added key should now coerce the ID to be `chegiobflhdjeloajcedlhenlemaekjp` which should work with the OAuth credential.
